### ISSUE TITLE
change website title

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/erddap-gold-standard#40]
Change the title `ERDDAP Quick Start` on https://ioos.github.io/erddap-gold-standard/index.html 
to 
`Quick Start Guide for ERDDAP in a Docker Container`

**Comment by MathewBiddle** [comment]
@BobSimons, how does this look?

![image](https://user-images.githubusercontent.com/8480023/193328198-8c48fe56-de6d-49c3-9079-b981301c23f5.png)

**Comment by BobSimons** [comment]
Excellent. Thanks.

**Comment by MathewBiddle** [comment]
Cool! Website has been updated https://ioos.github.io/erddap-gold-standard/
