### ISSUE TITLE
Update documentation to latest ERDDAP 2.23

### ISSUE THREAD

**Issue by callumrollo** [ioos/erddap-gold-standard#47]
The linked live demo runs ERDDAP 2.23, but the documentation and docker compose file are still on 2.18

I think this will require PRs to both master and gh-pages

**Comment by callumrollo** [comment]
This should be a case of replacing `axiom/docker-erddap:2.18` with`axiom/docker-erddap:latest-jdk17-openjdk` https://github.com/axiom-data-science/docker-erddap

**Comment by ocefpaf** [comment]
I know that it is harder to maintain buy I'd rather if the docs show a versioned way of handling your ERDDAP deployment. I would avoid "latest" b/c it hinders the version one is getting.

With that said, we should probably add a note saying:

    get `axiom/docker-erddap:2.23-jdk17-openjdk` or the latest one available.

that way the docs won't be "too" stale when we forget to update the ERDDAP version here.
