### ISSUE TITLE
+ basic setup info for docker

### ISSUE THREAD

**Issue by 7yl4r** [ioos/erddap-gold-standard#5]
It may be helpful to include some additional information on how to get ERDDAP set up on a new machine.
This might include:

1. how to install docker [(eg on ubuntu)](https://docs.docker.com/engine/install/ubuntu/)
2. [how to install docker-compose](https://docs.docker.com/compose/install/)
3. basics of setting up volumes using `docker-config.yml`

The README is already getting long. Should things be split into multiple `.md` documents here?

**Comment by MathewBiddle** [comment]
See https://ioos.github.io/erddap-gold-standard/index.html
