### ISSUE TITLE
master --> main

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/erddap-gold-standard#52]
Should we flip `master` to `main`?

I know quite a few folks who use this repo so the impacts might be more widespread than our other repos. But, I think it would be good to make the move.

**Comment by mwengren** [comment]
👍

**Comment by MathewBiddle** [comment]
It would be good to merge all the outstanding PRs before we do this. I'll see what I can close.

**Comment by ocefpaf** [comment]
> It would be good to merge all the outstanding PRs before we do this. I'll see what I can close.

GH should be able to point them to the new branch name without a problem. But it is nice to get them merged regardless.

**Comment by MathewBiddle** [comment]
Done.

# The default branch has been renamed!
`master` is now named `main`

If you have a local clone, you can update it by running the following commands.

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
