### ISSUE TITLE
upgrading from 2.18 to 2.23 not deploying using docker

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/erddap-gold-standard#62]
I was following the instructions at https://ioos.github.io/erddap-gold-standard/update-erddap.html to upgrade an ERDDAP from 2.18 to 2.23 (https://erddap.ioos.us/erddap/index.html). It seems that version 2.19 has one major TODO item:
> TO DO: ERDDAP now requires Java 17 and the related Tomcat 10. You must follow the ERDDAP installation instructions (or the equivalent e.g., for Docker) to install Java 17 and Tomcat 10 and copy your [tomcat]/content directory from your Tomcat 8 installation into the new [tomcat] directory.

I assumed (probably bad on my part) this was managed in the docker container and all I needed to do was update the container to the most recent one and things would work just fine. However, that's not the case. 

I know the most recent [commit](https://github.com/ioos/erddap-gold-standard/commit/479a1dc50e7ddc0340587cbea6abd1f39f54d2c5) moved the env vars to docker-compose. Is this a new requirement for deploying >v2.23 with Docker? 

I'm just trying to tease out if I need to move all my env variable declarations to docker-compose or if I need to do something else to satisfy the Java and Tomcat update...

**Comment by MathewBiddle** [comment]
What I've done:
1. Stopped the ERDDAP server: `docker-compose down`
2. Edited `docker-compose.yml` to point to the latest container https://github.com/ioos/erddap-gold-standard/blob/479a1dc50e7ddc0340587cbea6abd1f39f54d2c5/docker-compose.yml#L3 ours was still pointing to 2.18 from this commit https://github.com/ioos/erddap-gold-standard/blob/6528ef1b3e94f9a6b7c4c9294c2ac976a2656b6f/docker-compose.yml#L5
3. Save edits.
4. Spin up the container `docker-compose up -d`

Container looks like it's doing what it should but the logs aren't getting written and the website isn't resolving.

If I stop the container, revert back to 2.18, and start back up again, the ERDDAP spins up as expected. 

I think I'm missing something with how Java  changed between 2.18 and 2.23 and what might need to be adjusted within this repo. 

cc @mwengren

**Comment by MathewBiddle** [comment]
AHHA! I was hiding the docer-compose output with `-d`:
```
$ docker-compose up
Creating network "erddap-gold-standard_default" with the default driver
Creating erddap_gold_standard ... done
Attaching to erddap_gold_standard
erddap_gold_standard | ERDDAP running with:  -server -d64 -Xms1G -Xmx2G -XX:+HeapDumpOnOutOfMemoryError -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -DerddapContentDirectory=/usr/local/tomcat/content/erddap/ -Djna.tmpdir=/tmp/ -Djava.security.egd=file:/dev/./urandom
erddap_gold_standard | Unrecognized option: -d64
erddap_gold_standard | Error: Could not create the Java Virtual Machine.
erddap_gold_standard | Error: A fatal exception has occurred. Program will exit.
erddap_gold_standard exited with code 1
```

**Comment by MathewBiddle** [comment]
from erddap/conf/setenv.sh to remove `-d64`
```
NORMAL="-server -Xms1G -Xmx2G"                                                                                                                                                                                                                                                 HEAP_DUMP="-XX:+HeapDumpOnOutOfMemoryError"
HEADLESS="-Djava.awt.headless=true"
EXTRAS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
CONTENT_ROOT="-DerddapContentDirectory=$CATALINA_HOME/content/erddap"
JNA_DIR="-Djna.tmpdir=/tmp/"
FASTBOOT="-Djava.security.egd=file:/dev/./urandom"
```

Now I have this error:
```
$ docker-compose up
Starting erddap_gold_standard ... done
Attaching to erddap_gold_standard
erddap_gold_standard | groupadd: group 'tomcat' already exists
erddap_gold_standard | ERDDAP running with:  -server -Xms1G -Xmx2G -XX:+HeapDumpOnOutOfMemoryError -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -DerddapContentDirectory=/usr/local/tomcat/content/erddap/ -Djna.tmpdir=/tmp/ -Djava.security.egd=file:/dev/./urandom
erddap_gold_standard | Unrecognized VM option 'UseConcMarkSweepGC'
erddap_gold_standard | Error: Could not create the Java Virtual Machine.
erddap_gold_standard | Error: A fatal exception has occurred. Program will exit.
erddap_gold_standard exited with code 1
```

**Comment by MathewBiddle** [comment]
Seems like something here isn't working right?
https://github.com/axiom-data-science/docker-erddap/blob/4c4b510be4b87b30288eea0ab4a9632fc3009dc1/files/setenv.sh#L31-L35

**Comment by MathewBiddle** [comment]
Finally got it working! Here were the changes I had to make:

docker-compose.yml points to new image:
```bash
$ diff docker-compose.yml docker-compose.yml.20240130
5c5
<     image: axiom/docker-erddap:2.23-jdk17-openjdk
---
>     image: axiom/docker-erddap:2.18
```

`setenv.sh` removed `-d64` and `EXTRAS`:
```bash
$ diff erddap/conf/setenv.sh erddap/conf/setenv.sh.backup20240130
16c16
< NORMAL="-server -Xms1G -Xmx2G"
---
> NORMAL="-server -d64 -Xms1G -Xmx2G"
19c19
< #EXTRAS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
---
> EXTRAS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
```

Now we have 2.23 [running](https://erddap.ioos.us/erddap/index.html):
![image](https://github.com/ioos/erddap-gold-standard/assets/8480023/d41f84a8-3fad-4f37-a806-01bd40825d05)


The key to figuring this out was being able to trace what docker-compose was doing in https://github.com/ioos/erddap-gold-standard/issues/62#issuecomment-1917820340

**Comment by mwengren** [comment]
@MathewBiddle Glad you sorted it out! I'm not clear where you are editing the `setenv.sh` file, since that should be built into the Docker container from the source [setenv.sh](https://github.com/axiom-data-science/docker-erddap/blob/main/files/setenv.sh) file in axiom-data-science/docker-erddap, and it doesn't exist in this repo.

When I tried to run ERDDAP 2.23 via the standard Docker command in https://ioos.github.io/erddap-gold-standard/index.html#step-3-deploy-erddap-locally rather than Docker compose, it seemed to work properly out of the box, and [these lines in setenv.sh](https://github.com/axiom-data-science/docker-erddap/blob/main/files/setenv.sh#L32-L35) properly detected the Java version and skipped adding those parameters to the Java command.  Here's the relevant output from Docker:

```
ERDDAP_MAX_MEMORY=2G
ERDDAP_MIN_MEMORY=1G
ERDDAP Running with:  -server -Xms1G -Xmx2G -XX:+HeapDumpOnOutOfMemoryError -Djava.awt.headless=true  -DerddapContentDirectory=/usr/local/tomcat/content/erddap/ -Djna.tmpdir=/tmp/ -Djava.security.egd=file:$
dev/./urandom
```

The `setenv.sh` file is copied to the Docker image in [these lines of the Dockerfile](https://github.com/axiom-data-science/docker-erddap/blob/main/Dockerfile#L63-L64).  

It's odd that the behavior would be different when run with Docker Compose than with the standard Docker command.  Maybe it's because you were working off an existing ERDDAP Docker container that had an old version of `setenv.sh` hanging around that required updating?  I would have expected it to pull down a new image of 2.23 when you updated the `docker-compose.yml` file and rebuilt the container.  Strange.  I'm not too familiar with Docker Compose.  

Troubleshooting with `docker image ls` and `docker container ls -a` might help to understand what's going on.  Maybe we can take a look sometime.

**Comment by MathewBiddle** [comment]
> I'm not clear where you are editing the setenv.sh file, since that should be built into the Docker container from the source [setenv.sh](https://github.com/axiom-data-science/docker-erddap/blob/main/files/setenv.sh) file in axiom-data-science/docker-erddap, and it doesn't exist in this repo.

That's what I've been most confused about in this whole thing. I'll try to shutdown the container, move setenv.sh and see if a new setenv.sh is built when I start the container. 

Here is my `docker image ls`:
```bash
$ docker image ls
REPOSITORY            TAG                  IMAGE ID       CREATED         SIZE
axiom/docker-erddap   2.23-jdk17-openjdk   2e83e717aae3   2 months ago    1.32GB
axiom/docker-erddap   <none>               b33e965d8152   11 months ago   1.57GB
axiom/docker-erddap   2.18                 dda528a72b28   23 months ago   1.37GB
```

**Comment by MathewBiddle** [comment]
in my `docker-compose.yml` I mount that file into the container. 
```
"${PWD}/erddap/conf/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
```

**Comment by MathewBiddle** [comment]
Okay, I think that was the issue. I was mounting `setenv.sh` into the container so I could specify the various environment variables (admin contact stuff mainly). See https://github.com/ioos/erddap-gold-standard/blob/479a1dc50e7ddc0340587cbea6abd1f39f54d2c5/docker-compose.yml#L18-L38

I have now updated our `docker-compose.yml` to include those definitions and no longer mount in the `setenv.sh` file. The container spins up and runs as expected now.

**Comment by mwengren** [comment]
Great!  That explains it.  Specifying those env vars in docker-compose.yml is a better way to do that so that upstream changes in the container aren't missed.  That should make it easier to update going forward.
